typography_spectrum: 0.7135250670835376
color:
  brandStrength: 0.722221884643659
  lightness: 0.7101253410801291
  saturation: 0.5455529475584626
  rhythmicContrast: 0.4165233427193016
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.08905055839568377
author:
  name: Emily Hallinan
  email: emily@soultransformations360.com
  url: www.soultransformations360.com
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebec5f04-9dfa-4c00-b4a2-a2a48efba4c1.png'
name: Soul Transformations 360
title: Tune into your authentic self with emily hallinan
